# Generated by Django 4.1.5 on 2023-01-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inspecao', '0008_alter_seccao_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divisao',
            old_name='sec_id',
            new_name='sec',
        ),
        migrations.RenameField(
            model_name='seccao',
            old_name='inspec_id',
            new_name='inspec',
        ),
    ]
