# Generated by Django 4.1.5 on 2023-02-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspecao', '0009_rename_sec_id_divisao_sec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisao',
            name='freq2150',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='divisao',
            name='freq47',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='divisao',
            name='freq862',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='divisao',
            name='freq950',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='divisao',
            name='nome',
            field=models.CharField(default='Divisão', max_length=10),
        ),
    ]
