# Generated by Django 4.1.5 on 2023-03-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspecao', '0011_alter_divisao_nome_alter_inspection_ref_relatorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisao',
            name='freq47',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='divisao',
            name='freq862',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=8),
        ),
    ]
