# Generated by Django 4.1.5 on 2023-01-18 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_insp', models.DateField()),
                ('data_sub', models.DateField(auto_now_add=True)),
                ('endereco', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=30)),
                ('distrito', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('inpec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inspecao.inspection')),
            ],
        ),
        migrations.CreateModel(
            name='Divisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('freq47', models.DecimalField(decimal_places=1, max_digits=20)),
                ('freq862', models.DecimalField(decimal_places=1, max_digits=20)),
                ('freq950', models.DecimalField(decimal_places=1, max_digits=20)),
                ('freq2150', models.DecimalField(decimal_places=1, max_digits=20)),
                ('sec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inspecao.seccao')),
            ],
        ),
    ]
