# Generated by Django 4.1.5 on 2023-01-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inspecao', '0002_remove_inspection_cidade_remove_inspection_data_insp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='user',
        ),
    ]
