# Generated by Django 4.1.5 on 2023-01-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspecao', '0003_remove_inspection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='Ref_Relatorio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
