# Generated by Django 4.1.5 on 2023-01-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspecao', '0004_inspection_ref_relatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisao',
            name='freq2150',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='divisao',
            name='freq47',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='divisao',
            name='freq862',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='divisao',
            name='freq950',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='divisao',
            name='nome',
            field=models.CharField(default='Divisão', max_length=30),
        ),
    ]
