# Generated by Django 4.1.5 on 2023-01-25 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Inspecao', '0006_rename_inpec_id_seccao_inspec_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='Ref_Relatorio',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seccao',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
