# Generated by Django 4.1.5 on 2023-01-26 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Inspecao', '0007_alter_inspection_ref_relatorio_alter_seccao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccao',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
