# Generated by Django 4.1.5 on 2023-05-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspecao', '0012_alter_divisao_freq47_alter_divisao_freq862'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisao',
            name='freq47',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='divisao',
            name='freq862',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=8),
        ),
    ]
