# Generated by Django 4.1.5 on 2023-05-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inspecao', '0013_alter_divisao_freq47_alter_divisao_freq862'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divisao',
            old_name='freq2150',
            new_name='mesurement_point1',
        ),
        migrations.RenameField(
            model_name='divisao',
            old_name='freq47',
            new_name='mesurement_point2',
        ),
        migrations.RenameField(
            model_name='divisao',
            old_name='freq862',
            new_name='mesurement_point3',
        ),
        migrations.RenameField(
            model_name='divisao',
            old_name='freq950',
            new_name='mesurement_point4',
        ),
    ]
